### ISSUE TITLE
Custom table names?

### ISSUE THREAD

**Issue by taylor-smith** [robmiller/ruby-wpdb#24]
My WordPress database tables are prefixed by vpzd (e.g. wp_vpzd_posts). Is there any way to access tables whose names fall outside standard WordPress naming conventions?

**Comment by robmiller** [comment]
Sure — you can pass a different prefix when initializing ruby-wpdb:

`WPDB.init("mysql2://user:pass@localhost/foo", "wp_vpzd_")`

**Comment by taylor-smith** [comment]
I now see that clearly documented in the init function...d'oh. RTFC. Thank you so much for your help!

**Comment by robmiller** [comment]
No worries! It's not amazingly well-documented — I should probably put a note in the README about it.
